# https://wiki.hyprland.org/Configuring/
# source = ~/.config/hypr/myColors.conf

source = ~/.config/hypr/modules/colors.conf
source = ~/.config/hypr/modules/personal.conf
source = ~/.config/hypr/modules/looks.conf
source = ~/.config/hypr/modules/devices.conf
source = ~/.config/hypr/modules/keybinds.conf
source = ~/.config/hypr/modules/rules.conf
