# handle gestures binds
source = $HOME/.config/hypr/modules/inputs/gestures.conf

# handle keyboard binds
source = $HOME/.config/hypr/modules/inputs/01_variables.conf
source = $HOME/.config/hypr/modules/inputs/02_wm.conf
source = $HOME/.config/hypr/modules/inputs/03_app.conf
source = $HOME/.config/hypr/modules/inputs/04_workspaces.conf
source = $HOME/.config/hypr/modules/inputs/05_mouse.conf
source = $HOME/.config/hypr/modules/inputs/06_multimedia.conf
source = $HOME/.config/hypr/modules/inputs/07_louarch.conf
source = $HOME/.config/hypr/modules/inputs/08_submap.conf
