#################
### Variables ###
#################

# Modifier keys
$mainMod = ALT
$altMod = SUPER

# default keybinds/submap
submap = reset

# default programs
$terminal = wezterm
$fileManager = nautilus
