###############
### Windows ###
###############

# layout shortcuts
bind = $mainMod SHIFT, Q, killactive
bind = $mainMod, F, fullscreen
bind  = $mainMod SHIFT, V, togglefloating,
bind = $mainMod, SPACE, layoutmsg, togglesplit dwindle

# Move focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Move windows
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

# hold to resize
bindm = $mainMod, R, resizewindow
