###################
### Application ###
###################

# core shortcuts
bind = $mainMod, RETURN, exec, $terminal
bind  = $altMod, L, exec, pidof hyprlock || hyprlock
bindr = $mainMod, D, exec, pkill rofi || rofi -show drun
bindr = $mainMod SHIFT, D, exec, pkill rofi || rofi -show window
bindr = $altMod, V, exec, pkill wofi || ~/.config/hypr/scripts/hyprscripts.sh clipboard
bindr = $altMod, P, exec, pkill wlogout || wlogout

# extra shortcuts
bind = $altMod, E, exec, $fileManager
bind = $altMod, F, exec, firefox
bind = $altMod, B, exec, brave
bind = $altMod SHIFT, B, exec, chromium
bind = $altMod SHIFT, F, exec, firefox -private-window
bind = $altMod SHIFT, S, exec, localsend
bind = $altMod, N, exec, swaync-client -t -sw

# Special workspaces apps
bind = $altMod, S, exec, pgrep spotify && hyprctl dispatch togglespecialworkspace Spotify || spotify-launcher
bind = $altMod, C, exec, pgrep gnome-calculato && hyprctl dispatch togglespecialworkspace Calculator || gnome-calculator
bind = $altMod, G, exec, pgrep steam && hyprctl dispatch togglespecialworkspace Steam || steam

# reload and testing
bind = $altMod, TAB, exec, pkill -SIGUSR1 waybar
bind = $mainMod SHIFT, R, exec, pkill waybar & hyprctl dispatch exec waybar
bind = $mainMod, N, exec, wezterm start nvim ~/private/quicknotes.md

# screenshot and color picker shortcuts
bind = , PRINT, exec, hyprshot -m region
bind = $mainMod, PRINT, exec, hyprshot -m window
bind = $altMod, PRINT, exec, hyprshot -m output
bind = $altMod SHIFT, PRINT, exec, hyprshot -m active -m  output

bindr = $mainMod, P, exec, hyprpicker -a

# handle hyprlock bug
bindl = CTRL ALT, L, exec, /bin/bash -c "hyprctl notify 1 2000 0 'oopsies'; hyprctl --instance 0 dispatch exec killall hyprlock dms; sleep 0.2; hyprctl --instance 0 keyword misc:allow_session_lock_restore 1; sleep 0.2; hyprctl --instance 0 dispatch exec hyprlock; sleep 1; hyprctl --instance 0 keyword misc:allow_session_lock_restore 0"
