#############
### Mouse ###
#############

# Workspace scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Window management
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# side buttons
bind = , mouse:276, exec, louarch audio sink
bind = , mouse:275, exec, hyprlock --immediate
bind = $mainMod, mouse:275, exec, hyprctl dispatch workspace e+1
bind = $mainMod, mouse:276, exec, hyprctl dispatch fullscreen 0
