#######################
### Louarch Actions ###
#######################

# custom scripts shortcuts
# refer to: https://github.com/yashodhanketkar/louarch

# handle audio devices
bind = , 179, exec, louarch audio sink
bind = $altMod, A, exec, louarch audio sink
bind = $altMod SHIFT, A, exec, louarch audio source

# handle browser shortcuts
bindr = $mainMod, S, exec, louarch browser search
bindr = $mainMod, O, exec, louarch browser browse

# handle toggle-able mode
bind = $mainMod, G, exec, louarch osmode game
bind = $altMod, M, exec, louarch osmode night

# handle wallpapers
bind = $altMod, W, exec, louarch wallpaper select
bind = $altMod SHIFT, W, exec, louarch wallpaper random
