###############
### submaps ###
###############

# submap declarations
bind = $altMod, R, submap, resize
bind = $altMod, T, submap, trading

# Resize windows with keyboard
submap = resize
  bindm = , R, resizewindow
  binde = , L, resizeactive, 10 0
  binde = , H, resizeactive, -10 0
  binde = , K, resizeactive, 0 10
  binde = , J, resizeactive, 0 -10

  binde = SHIFT, L, resizeactive, 50 0
  binde = SHIFT, H, resizeactive, -50 0
  binde = SHIFT, K, resizeactive, 0 50
  binde = SHIFT, J, resizeactive, 0 -50
bind = , ESCAPE, submap, reset

# Tradingview (disable Conflicting keybinds)
submap = trading
  unbind = , H
  unbind = , J
  unbind = , K
  unbind = , L
bind = SUPER, ESCAPE, submap, reset
