###############
### GESTURE ###
###############

# https://wiki.hyprland.org/Configuring/Variables/#gestures

# foucs related
gesture = 3, horizontal, workspace
gesture = 3, vertical, fullscreen

# movement related
gesture = 4, pinch, resize
gesture = 4, vertical, mod: SUPER, float
gesture = 4, vertical, mod: ALT, move
gesture = 4, horizontal, mod: ALT, move
