require("hyprland.keybinds.apps")
require("hyprland.keybinds.windows")
require("hyprland.keybinds.recovery")
require("hyprland.keybinds.media")
require("hyprland.keybinds.gestures")
require("hyprland.keybinds.submaps")
require("hyprland.keybinds.louarch")
require("hyprland.keybinds.specialworkspace")
